services:
  database:
    container_name: database
    volumes:
      - db-data:/var/lib/postgresql/data/
    build: database
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
  bot:
    container_name: bot
    build: bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - database
volumes:
  db-data:
